### ISSUE TITLE
Gouvernance pour la production des données

### ISSUE THREAD

**Issue by fvanhoutte** [etalab/amenagements-cyclables#17]
Quelle est la gouvernance prévue autour de la production des données ?

En clair, comment est il prévu de gérer lorsque la base est produite plusieurs fois :
1. par la collectivité qui a la compétence pour aménager (la voirie) dans ses outils et placée en opendata
2. par des associations locales sur des outils proposés par le PAN ou par association nationale
3. par des usagers particuliers sur OSM ?

**Comment by bchartier** [comment]
Lors du webinaire aujourd'hui cette question a été posée. La réponse qui a été donnée par les conférenciers lors de cet évènement était (désolé pour la synthèse peut-être maladroite) : "lorsque un même aménagement est décrit plusieurs fois par des contributeurs différents sera retenue la description de la collectivité". Personnellement, je ne sais pas si c'est un bon choix et, si c'est un bon choix, je ne sais pas comment cela pourrait être mis en place sans avoir connaissance de qui/quoi possède la compétence sur tel ou tel aménagement. Aujourd'hui on a un code commune dans le modèle de données mais visiblement il est fait pour connaître le code insee de la commune sur lequel l'aménagement est localisé mais ne dit rien de qui en a la responsabilité.

**Comment by fvanhoutte** [comment]
Pour fluidifier la gouvernance des données, un tag supplémentaire sur le gestionnaire / organisme compétent sur l'aménagement parrait effectuvement judicieux. Il permettra, en cas de remontée multiple de données d'un aménagement, de privilégier la source du producteur gestionnaire / aménageur. Ca permettrait de fait, sur un territoire, la remontée des aménagements cyclables des départements comme des intercommunalités en filtrant l'aggrégation sur leur périmètre de responsabilité. A défaut serait utiliser les données d'un organisme officiel, puis dans un degré moindre, des contributeurs publics en cas de carrence des producteurs institutionnels

**Comment by Juliette-Martin** [comment]
En plus d’identifier un « producteur supra », l’indication de gestionnaire aurait également l’utilité de pouvoir orienter les remontées usagers. Le standard est à destination de l’info voyageur, on peut imaginer dans un avenir proche la possibilité de signaler des anomalies. Cette information permettrait de les diriger vers la bonne structure. Au vue de la répartition actuelle des compétences, identifier le gestionnaire d’un aménagement cyclable nécessite une connaissance fine de l’organisation locale.

**Comment by Miryad3108** [comment]
Bonjour, 

Pour l'instant, nous agrégerons toutes les données sur les aménagements cyclables qui seront publiées. Nous choisirons ensuite quelle gouvernance adoptée selon les retours et besoins des réutilisateurs. 

Concernant le nom du gestionnaire, ce champ était dans la première version du schéma mais n'a pas été retenu par le groupe de travail. Si vous voulez soumettre de nouveau le vote, vous pouvez faire une proposition d'amélioration en suivant ce tutoriel : https://doc.transport.data.gouv.fr/producteurs/amenagements-cyclables/contribution-au-schema-sur-les-amenagements-cyclables

**Comment by fvanhoutte** [comment]
Bonjour. merci pour le retour.

2 remarques complémentaires :

- A long terme, sauf à considérer qu'un seul outil sera amené à servir d'IHM pour produire l'information, il faudra bien résoudre cette question. Comment impliquer un acteur public qui aménage l'espace si son rôle de producteur et gestionnaire d'information n'est pas reconnu ? On déjà pas mal vécu de situations compliquées sur d'autre sujet par le passé qui ont montré que ce point n'est pas à négliger.

- je sais que 2 univers se rencontrent (opendata / geomaticien) et pour ces derniers le processus pour vous retourner des propositions peut constituer un frein je pense.

**Comment by fvanhoutte** [comment]
Je rebondis sur cette question à la vue du projet sur le stationnement cyclable.
Ce dernier prévoit bien des attributs `proprietaire` et `gestionnaire` pour gérer notamment les cas évoqués précédemment.
https://github.com/etalab/schema-stationnement-cyclable/blob/master/schema.json

Dans un souci de cohérence et afin d'urbaniser les schémas de données, il me semble important d'ajouter ces attributs sur le schéma aménagement cyclable.

Merci

**Comment by Miryad3108** [comment]
Bonjour, 
Pouvez vous faire la demande d'ajout des attributs `proprietaire` et `gestionnaire`  sous forme de Pull Request afin de faire voter cette proposition ? 
Vous trouverez un tuto de contribution au schéma national des aménagements cyclables ici : https://doc.transport.data.gouv.fr/producteurs/amenagements-cyclables/contribution-au-schema-sur-les-amenagements-cyclables


Bien à vous,
