### ISSUE TITLE
Champ code_com

### ISSUE THREAD

**Issue by bchartier** [etalab/amenagements-cyclables#20]
Je me pose la question de l'utilité du champ `code_com`.
De toute évidence il ne sert pas à se localiser puisque l'on a une géométrie associée à chaque aménagement.
Ce champ est obligatoire et ne peut contenir qu'une seule commune ce qui est problématique pour les cas où la chaussée peut constituer une limite entre deux communes.
De plus il contraint le producteur à découper son réseau à chaque limite de commune de manière artificielle.

À titre personnel, j'aurais tendance à retirer ce champ. À moins qu'il existe un usage de ce champ indissociable de ce type de jeu de données. Si tel est le cas il faudrait le documenter.
S'il faut conserver cette information alors il faut trouver un moyen pour renseigner le code d'une commune à droite et à gauche.

**Comment by Miryad3108** [comment]
Bonjour, 

Je vous remercie pour votre remarque. 

A la suite du Webinaire de Vélo & Territoires qui a eu lieu ce matin, nous allons : 
- modifié le code_com pour en avoir un à droite et à gauche, comme vous le préconisez ;
Cela permettra d'avoir une vision à l'échelle communale du nombre et types d'aménagements cyclables. 
- développé un modèle de données pour faciliter la prise en main du modèle de données ;
- publié une foire à questions qui se basera notamment sur les questions posées lors du Webinaire.

**Comment by bchartier** [comment]
> * développé un modèle de données pour faciliter la prise en main du modèle de données ;

Je pense qu'il y a un "modèle de données" en trop dans cette phrase et qu'il a remplacé un autre terme que je n'arrive pas à deviner.

Autre raison pour laquelle je n'aime pas trop le code commune ici : code commune peuvent changer localement (des territoires peuvent changer de commune, de département, des communes peuvent fusionner ou se scinder...). Ce serait dommage de devoir mettre à jour des données à chaque évènement de ce type alors que la plus-value de cette information ne me semble pas claire.

**Comment by NicolasBerthelot** [comment]
Je partage votre point de vue sur la difficulté de maintenir cette information et les conséquences qu'elle peut avoir sur la modélisation des tronçons (couper à chaque commune les tronçons peut être ennuyeux). Il semblait intéressant de conserver cet attribut dans la perspective d'analyses à la maille commune/EPCI/Département sans faire intervenir de traitement géomatique. Cependant l'absence de champ "longueur du tronçon" dans le schéma limitera fortement les analyses pouvant être faites sans traitement géomatique. 
Si un tel champ venait à être intégré j'aurais tendance à être favorable au maintien d'un champ code_commune au moins dans les bases nationales de manière exhaustive. Sans un champ "longueur_du_tronçon" je suis plutôt du parti de ne pas collecter et produire de manière obligatoire cette information.

**Comment by bchartier** [comment]
Merci.

**Comment by Phamb38** [comment]
> S'il faut conserver cette information alors il faut trouver un moyen pour renseigner le code d'une commune à droite et à gauche.

Ca pré-suppose qu'il y aurait beaucoup de cas de figure de voies qui sont séparées en 2 (dans la longueur) avec à droite une commune qui gère un aménagement cyclable et à gauche une autre commune qui gère l'autre ? 
Ca me paraît lourd de démultiplier cet attribut (surtout du fait de son statut "obligatoire").

**Comment by bchartier** [comment]
> > S'il faut conserver cette information alors il faut trouver un moyen pour renseigner le code d'une commune à droite et à gauche.
> 
> Ca pré-suppose qu'il y aurait beaucoup de cas de figure de voies qui sont séparées en 2 (dans la longueur) avec à droite une commune qui gère un aménagement cyclable et à gauche une autre commune qui gère l'autre ?

Remarque intéressante à deux titres :
* Le champ `code_com` tel qu'indiqué précédemment dans le schéma (ou maintenant `code_com_g` et `code_com_d`) n'est pas là pour identifier le gestionnaire de l'aménagement mais simplement la commune dans laquelle l'aménagement est présent. Voir la description présente dans le schéma : "Code INSEE de la commune (5 caractères alphanumériques) sur la voie de droite" par exemple.
* Doit-on se mettre en difficulté en imposant un seul champ obligatoire alors que l'on sait d'avance qu'un seul champ n'est pas adapté à la gestion de certains cas particuliers ? Doit-on élaborer un modèle de données uniquement pour la grande majorité des cas ?

> Ca me paraît lourd de démultiplier cet attribut (surtout du fait de son statut "obligatoire").

Le dédoublement des champs concerne plusieurs informations du schéma. Cette situation découle du fait qu'une seule géométrie est utilisée pour les deux sens de circulation d'un même axe routier. Je regrette ce choix car il me semble contradictoire avec le fait de décrire correctement la connectivité des aménagements cyclables avec le reste du réseau routier (ce qui pourrait être utile pour des besoins de calcul d'itinéraires adaptés aux cycles). Pour moi cela est en contradiction avec l'un des objectifs affichés : "... permettant à des services de calcul d’itinéraire d’intégrer ces données". Si chaque aménagement avait sa propre géométrie nous n'aurions pas ce dédoublement et tout serait sans doute plus simple pour une gestion à une grande échelle cartographique. Dans le cas présent on semble privilégier les moyennes échelles et le calcul d'indicateurs. Mais je peux me tromper...

**Comment by bchartier** [comment]
D'ailleurs, la question du dédoublement risque de se poser pour de nouveaux champs : #18.

**Comment by bchartier** [comment]
> Le dédoublement des champs concerne plusieurs informations du schéma. Cette situation découle du fait qu'une seule géométrie est utilisée pour les deux sens de circulation d'un même axe routier. Je regrette ce choix car il me semble contradictoire avec le fait de décrire correctement la connectivité des aménagements cyclables avec le reste du réseau routier (ce qui pourrait être utile pour des besoins de calcul d'itinéraires adaptés aux cycles). Pour moi cela est en contradiction avec l'un des objectifs affichés : "... permettant à des services de calcul d’itinéraire d’intégrer ces données". Si chaque aménagement avait sa propre géométrie nous n'aurions pas ce dédoublement et tout serait sans doute plus simple pour une gestion à une grande échelle cartographique. Dans le cas présent on semble privilégier les moyennes échelles et le calcul d'indicateurs. Mais je peux me tromper...

Cette partie de mon commentaire n'est peut-être pas pertinente car je n'avais pas vu cette précision : https://github.com/etalab/schema-amenagements-cyclables/issues/21#issuecomment-788736466

**Comment by Juliette-Martin** [comment]
> Ca pré-suppose qu'il y aurait beaucoup de cas de figure de voies qui sont séparées en 2 (dans la longueur) avec à droite une commune qui gère un aménagement cyclable et à gauche une autre commune qui gère l'autre ?

Sur le territoire où je travaille les limites de communes suivent en majorité des cours d'eau ou des chemins. Le cas de figure n'est pas anecdotique sur certains territoires, ruraux notamment. Heureusement bien souvent les communes s'arrangent pour l'entretien et ne viennent pas faucher que leur côté ☺. Mais on a bien un côté du chemin sur une commune et l'autre sur la commune voisine.
