### ISSUE TITLE
Documentation (précisions)

### ISSUE THREAD

**Issue by gregbodet** [etalab/amenagements-cyclables#34]
Bonjour,

Après lecture attentive de votre documentation, j'aurais quelques questions concernant :
- le type de réseau local : pouvez-vous apporter des définitions sur les valeurs REV, STRUCTURANT ET AUTRE,
- l'accéssibilité des aménagements par type de véhicule non motorisé : une seule valeur n'est possible ? Celle-ci donne-t-elle par défaut l'accès aux autres ? (ex : si ROLLER donc utilisable par VTT, VTC et VELO DE ROUTE ?
- la localisation de l'aménagement (à gauche ou à droite) : à quoi correspond la valeur INTERMEDIAIRE
- la projection cartographique de la donnée source : ne faut-il pas indiquer Lambert 93 ou la code EPSG
- nous notons des incohérences entre les attributs obligatoires ou non (fond vert clair ou vert foncé) entre la structure décrite page 5 à 8 et les exemples données.

Cordialement

**Comment by fcommeaux** [comment]
Bonjour, et merci pour ces remarques, voici quelques éléments de réponse : 
- Le champ reseau_local vise à hiérarchiser les différents types de réseaux vélo (REV : Réseau Express Vélo, Structurant ou autre)
- Effectivement les valeurs possibles du champ acces_ame sont ordonnées comme suit : ROLLER > VELO DE ROUTE > VTC > VTT – Une seule valeur est donc suffisante. Nous allons mettre à jour la notice de numérisation pour apporter plus de clarté sur ce champ. 
- La valeur INTERMEDIAIRE des champs local_d/local_g permet d’indiquer que la cote de l’aménagement cyclable se situe entre celle de la chaussée et celle du trottoir. 
- Le champ project_c est un champ libre dans lequel toute indication sur la projection cartographique de la donnée source a sa place, que ce soit sous la forme d’un code (EPSG -2154) ou d’une indication en toute lettre (Lambert 93).
- Effectivement il peut y avoir une confusion dans la notice de numérisation : le code couleur indiqué dans la revue des champs n’est pas utilisé dans les exemples de numérisation. Cela sera rectifié rapidement dans une prochaine version de cette notice.
