### ISSUE TITLE
Axe de numérisation (questionnement)

### ISSUE THREAD

**Issue by gregbodet** [etalab/amenagements-cyclables#35]
Bonjour,

Après lecture de la documentation sur la démarche de numérisation, nous nous posons la question de savoir comment numériser un aménagement cyclable séparée de la voie de circulation par du stationnement et/ou un espace végétalisé (cf illustration ci-dessous). Faut-il dans ce cas, utiliser le principe du cas 2 ?

![ame_cyclable](https://user-images.githubusercontent.com/37414914/120206940-1618b680-c22c-11eb-9013-1ce065257871.png)

Cordialement

**Comment by Juliette-Martin** [comment]
Bonjour,

Je me pose la même question. 

Pour le moment j'utilise l'axe principal si l'aménagement qu'il soit sur la chaussée ou sur le trottoir n'est pas physiquement séparé de la voie de circulation. Lorsqu'il y a des arbres et ou du stationnement, je le numérise sur son axe propre. 
C'est ce que je ferai dans le cas que vous évoquez ci-dessus.

Pour info, une extraction des aménagements cyclables issus de la base osm et restituée selon le standard par Géovélo est disponible sur le PAN : https://transport.data.gouv.fr/datasets/amenagements-cyclables-france-metropolitaine/

**Comment by Juliette-Martin** [comment]
Bonjour,
La FAQ semble donner la réponse à votre question : numérisation de l'aménagement sur son axe propre.

https://doc.transport.data.gouv.fr/producteurs/amenagements-cyclables/foire-a-questions :
"Le schéma ne fait pas de distinction entre site propre et site partagé. Il prévoit que les aménagements qui jouxtent une voirie de circulation soient numérisés sur l'axe de cette voirie, et non sur leur axe propre. Toutefois, il n'existe pas toujours une voirie adjacente, ou **cette voirie peut parfois être séparée par un terre-plein plus ou moins large**. Dans ces cas là il est recommandé de numériser l'aménagement sur son axe propre. Cela peut classiquement concerner :
- Piste cyclable
- Voie verte
- Aménagement mixte piéton/vélo hors voie verte
- Autre
