### ISSUE TITLE
Casse des valeurs exportées

### ISSUE THREAD

**Issue by gregbodet** [etalab/amenagements-cyclables#36]
Bonjour,

Dans votre documentation, et dans les exemples de valeurs à renseigner, vous indiquez la plupart du temps de valeurs en majuscule.
Cette casse est-elle obligatoire ou peut-on indifféremment mettre minuscule ou majuscule ? Nous posons cette question car certains attributs apparaissent en minuscule.

Cordialement

**Comment by fcommeaux** [comment]
Bonjour et merci pour votre question :
Pour tous les champs contraints par une liste de valeurs, la recommandation est effectivement d’utiliser les majuscules. Pour les autres ça n’a pas d’importance.
