### ISSUE TITLE
Intégration valeur "impasse mode doux" catégorie "ame_d/g"

### ISSUE THREAD

**Issue by bferretti57** [etalab/amenagements-cyclables#44]
Bonjour, 

Suite à la mise à jour du jeu de données sur le territoire de Metz, les perméabilités de type "impasse mode doux" (cf. panneau de signalisation réglementaire) sont difficiles à renseigner vu que ce type d'aménagement n'est pas prévu dans la liste. 

Plutôt que de l'indiquer en "autres", ne serait-il pas nécessaire d'ajouter cette variable aux catégories "ame_d" et "ame_g"?   

Merci de votre retour, bonne journée.

**Comment by Miryad3108** [comment]
Bonjour, 

Je vous remercie pour votre contribution et vous invite à faire une demande d'évolution du schéma sous forme de Pull Request. Vous trouverez un tutoriel détaillé sur la contribution au schéma : https://doc.transport.data.gouv.fr/producteurs/amenagements-cyclables/contribution-au-schema-sur-les-amenagements-cyclables

Vous pouvez notamment reprendre la demande d'évolution du schéma de Michael : https://github.com/etalab/schema-amenagements-cyclables/pull/46 


N'hésitez pas à revenir vers nous si vous rencontrez des difficultés.


Bien à vous,
