### ISSUE TITLE
Remplir les code INSEE d'un aménagement cyclable hors territoire communal

### ISSUE THREAD

**Issue by mboutry** [etalab/amenagements-cyclables#69]
On est clairement sur un cas très particulier, mais comment gérer les code INSEE des aménagements cyclables d'une voirie située hors territoire communal ?

Mon exemple est simple : le pont de l'Ile de Ré, qui possède une piste cyclable, relie deux communes entre elles mais n'est pas situé **sur ** une commune.
Naturellement j'affecte pour le moment le code INSEE de La Rochelle, puisque le champ est obligatoire.

Je pose la question car le "problème" pourrait se reposer ailleurs : autre pont (ne serait-ce que celui de l'Ile d'Oléron pour rester dans le 17), tunnel, autre...

**Comment by Miryad3108** [comment]
Bonjour @mboutry 

"Mon exemple est simple : le pont de l'Ile de Ré, qui possède une piste cyclable, relie deux communes entre elles mais n'est pas situé **sur ** une commune." : si je comprends bien, la piste relie deux communes et se situe donc sur les deux communes et non pas sur une commune ? 

Nous recommandons de scinder l'aménagement traversant plusieurs communes en autant d'objets géométriques, et ce même si l’aménagement est physiquement continu. cf : https://www.velo-territoires.org/wp-content/uploads/2021/03/AC_NOTICE_NUMERISATION_0.3.0.pdf (page 14).

**Comment by maxboutry** [comment]
Bonjour, @Miryad3108,

La piste relie bien deux communes (La Rochelle et Rivedoux-plage, sur l'Ile de Ré) mais se situe bien sur aucune commune.

![Exemple Pont Ré](https://user-images.githubusercontent.com/48677445/157617058-692432fc-5f73-4965-acf1-42abfad57421.jpg)

C'est plus pour alerter sur un cas particulier qui peut se reposer ailleurs et poser d'éventuels problèmes en termes de réutilisation que pour trouver une véritable solution technique dans le cadre du schéma. La solution de choisir "arbitrairement" d'affecter le code INSEE d'une des deux communes nous convient bien.
