### ISSUE TITLE
Formule pour remplir le champ id_local avec un identifiant unique 

### ISSUE THREAD

**Issue by mboutry** [etalab/amenagements-cyclables#70]
Bonjour,

Je créé actuellement les aménagements cyclables sous maitrise d'ouvrage départementale de la Charente-Maritime. J'utilise Qgis et le script SQL fourni avec le schéma sous PostGis. Ce script induit une contrainte de valeur non nulle et unique sur le champ id_local, qui se trouve être de type "chaîne de caractères". En l'état cela constitue un point de blocage.
Est-ce qu'il est possible de fournir une formule pour auto-incrémenter cet identifiant ?

Plus compliqué, je souhaiterais pour chaque nouvel aménagement remplir ce champ avec la mention "CD17_" puis un numéro incrémenté automatiquement. Cela donnerait par exemple : "CD17_00001" pour le premier aménagement, "CD17_00002" pour le 2ème aménagement et ainsi de suite. A défaut d'avoir des champs propriétaire/gestionnaire pour le moment, cette mention permettrait de (re)connaitre à minima et directement dans l'outil de visualisation (ON3V par exemple) le producteur de la donnée.
Est-ce possible et avec quelle formule ? 

Merci d'avance,

**Comment by smevel** [comment]
Bonjour
Sous QGiS, vous pouvez créer une valeur incrémentale par défaut dans le formulaire d'attributs.
Exemple :  concat('CD17_',lpad(count($id)+1, 5, 0))
ou en utilisant le champ propriétaire/gestionnaire à la place de CD17
![capture](https://user-images.githubusercontent.com/22056698/148090813-b2589066-00bd-46d0-aed6-7c4491b31932.png)

**Comment by mboutry** [comment]
Merci pour la réponse rapide. C'est exactement la formule que je cherchais, et je pense qu'elle pourra servir pour d'autres producteurs.

En revanche, cocher la case "Appliquer la valeur par défaut sur la mise à jour" peut poser des problèmes en cas de suppression d'un aménagement ou de mise à jour ultérieure.

**Comment by Miryad3108** [comment]
Bonjour, 

Merci @smevel pour votre réponse.
Nous ajouterons cette question/réponse à la [FAQ des aménagements cyclables](https://doc.transport.data.gouv.fr/producteurs/amenagements-cyclables/foire-a-questions) 🎉​
