### ISSUE TITLE
Ajout d'un type d'aménagement "traversée"

### ISSUE THREAD

**Issue by MarineTnr** [etalab/amenagements-cyclables#75]
Bonjour,

Nous avons une donnée sur les aménagements cyclables que nous modifions pour qu'elle corresponde au schéma national des aménagements cyclables. Cependant notre donnée précise s'il s'agit d'un aménagement de traversée de voirie, que l'on ne retrouve pas dans le schéma national.

Serait-il possible de rajouter une occurrence "TRAVERSEE" dans les types d'aménagement pour décrire les traversées de voiries sécurisées par des traçages au sol et signalisation ?

**Comment by Miryad3108** [comment]
Bonjour Marine, 

Je vous remercie pour cette proposition. 

Nous allons communiquer sur cette proposition d'ajout de valeur à l'énumération des champs `ame_d` et `ame_g` au schéma national des aménagements cyclables. 
Dès lors que nous aurons communiquer dessus, les participants auront 14 jours pour commenter votre proposition puis vous devrez poster un message pour lancer les votes. Ces votes seront ouverts pendant 10j. Plus d'informations [ici](https://doc.transport.data.gouv.fr/producteurs/amenagements-cyclables/contribution-au-schema-sur-les-amenagements-cyclables)

**Comment by axelos** [comment]
Bonjour,

Pouvez-vous plus concrètement indiquer ce qu’est un « aménagement de traversée de voirie » ?
Le nom me fait penser à une équivalence de trottoir traversant, pour cycles. Exemple sur cette page du Cerema, Chapitre 8, «Trottoir-piste traversant » : https://www.cerema.fr/fr/actualites/8-recommandations-reussir-votre-piste-cyclable

Si ce n’est pas le cas, il sera judicieux d’éviter les similitudes aux nommages de fonctions différentes.

Axel.

**Comment by EmmanuelRoche** [comment]
Bonjour,

Je suis sceptique sur l'intérêt de cette "traversée".
Si on prend l'exemple d'une voie verte qui traverse une voirie, on aura 2 objets de chaque côté de la voirie décrits comme "voie verte", et je ne me vois pas descendre à un niveau inférieur pour créer un 3e objet qui décrit la traversée elle-même sur 5 ou 10 mètres : on est à une échelle trop fine pour relever du SIG.
De plus en terme de topologie il faut pouvoir raccorder les 2 objets voie verte à l'objet voirie ; si on insère l'objet complémentaire traversée ça va compliquer les choses.
Dons avis plutôt défavorable pour ma part.

Emmanuel

**Comment by benoitmdp** [comment]
Bonjour,

Cela m'est également peu clair. Serait-ce un ajout de champ spécifique plutôt que ame_d ou ame_g ?
Est ce que c'est pour identifier en carrefour les cheminements cyclables "matérialisés" au sol entre deux aménagements cyclables ? ou est ce pour identifier toutes les discontinuités dans un aménagement ? donc par exemple tous les endroits où une piste cyclable n'est pas physiquement protégée par un séparateur ou en site propre.
A quoi serait-ce équivalent dans OSM ?

Benoît

**Comment by MarineTnr** [comment]
Bonjour,

Nous sommes en territoire rural avec notamment un réseau de voies vertes qui est séparé de la voirie. Il est intéressant pour nous d’identifier les intersections de ce réseau de voies vertes avec les voiries car on y trouve des aménagements spécifiques comme notamment des marquages au sol de traversée. Cela nous permet d’identifier les lieux sur lesquels se trouvent ces aménagements pour en assurer la maintenance par exemple. Ainsi, nous avons découpé nos tronçons d'aménagement pour que ressorte les aménagements de traversées de voirie. 
Cela pourrait peut-être permettre d'évaluer plus facilement la sécurité des aménagements cyclables aux calculateurs d'itinéraires cyclables.

Pour OSM, l'équivalence pourrait être highway=crossing qui décrit les passages traversant la voirie à l'usage des piétons et cyclistes.

Marine

**Comment by Miryad3108** [comment]
Bonjour, 

Je demande par la présente un vote sur cette proposition. Le vote sera ouvert pendant 10 jours civils complets jusqu'à 23 h UTC+2 à partir de ce jour. Il prendra donc fin le 27/06/2022 à 23h59. 

Veuillez voter pour ou contre la proposition, inclure l'organisation pour laquelle vous votez et préciser si vous êtes producteur ou réutilisateur dans votre commentaire.

Pour rappel, vous trouverez les différentes étapes d'une proposition d'évolution d'un schéma [ici](https://doc.transport.data.gouv.fr/producteurs/amenagements-cyclables/contribution-au-schema-sur-les-amenagements-cyclables) 


Bien à vous,

**Comment by EmmanuelRoche** [comment]
Bonjour,

Je vote contre cette modification.

Bien cordialement,

Emmanuel ROCHE - Grand Chambéry (producteur de données)

**Comment by Miryad3108** [comment]
Bonjour, 

Le vote pour cette issue se termine dans 2 jours calendaires. 
Veuillez voter pour ou contre la proposition et inclure l'organisation pour laquelle vous votez dans votre commentaire. 
Veuillez noter si vous pouvez vous engager à mettre en œuvre la proposition.

**Comment by benoitmdp** [comment]
Je suis opposé à cette issue. 
Ce serait plutôt un **champ supplémentaire** qui indique la présence du carrefour plutôt qu'une caractérisation de l'aménagement en tant que carrefour.

Bien cordialement

Benoît - Mairie de Paris
