### ISSUE TITLE
Où trouver la description de chaque champs de AC_TEMPLATE_SHP_QGIS

### ISSUE THREAD

**Issue by pgpaulgilbert** [etalab/amenagements-cyclables#77]
bonjour,

Où pouvons-nous trouver un document expliquant l'ensemble des champs la couche SIG AC_template_shp_QGIS. 

merci

**Comment by fabien-VT** [comment]
Bonjour,
Vélo & Territoires propose une notice de numérisation pour ce schéma de données :
https://www.velo-territoires.org/ressources/categorie/documents-techniques/?resource-id=18582#resource-amenagements-cyclables
