### ISSUE TITLE
Validation de date_maj

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/amenagements-cyclables#78]
Il n'y a pas de validation stricte actuellement, seulement string + consigne de notation.

Possible d'indiquer `"format": "date"` en plus, voir [ceci](https://stackoverflow.com/a/48664720/2645887)

https://github.com/etalab/amenagements-cyclables/blob/a75e9502b866eeaff68c15148f5eff6d5fb3cc8c/schema_amenagements_cyclables.json#L279-L285

**Comment by Miryad3108** [comment]
C'est ajouté avec la PR #83
Merci @AntoineAugusti
