### ISSUE TITLE
Mise à jour de AC_TEMPLATE_SHP_QGIS

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/amenagements-cyclables#79]
Hello,

Fabienne Le Hir du Conseil Départemental du Finistère indique que ce template QGIS comporte quelques erreurs par rapport au schéma, ce qui fait que les fichiers produits par ce biais ne sont pas valides ensuite.

Je ne connais ce format/l'outil en général. Pourrais-tu refaire une passe sur le fichier par rapport au schéma et vérifier que les configurations de chaque champ sont correctes ?

**Comment by AntoineAugusti** [comment]
Voir e-mail "Aménagements cyclables - Validateur de test de jeux de données", Fabien COMMEAUX de Vélo & Territoires est l'auteur du fichier original et devrait le modifier puis le transmettre.

**Comment by Miryad3108** [comment]
Merci @AntoineAugusti 
Fabien a corrigé le template et j'ai remplacé (cf PR #80 et PR #82)
